name = "thread-note-frontend"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# NOTE: Production environment
[env.production]
name = "thread-note-frontend-production"

# NOTE: Staging environment
[env.staging]
name = "thread-note-frontend-staging"
