# TODO: Update to the current situation

name = "thread-note-backend"
main = "src/worker.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# NOTE: D1 Database binding
# Run `wrangler d1 create thread-notes-db` to create the database
# Then update the database_id below with the generated ID
[[d1_databases]]
binding = "DB"
database_name = "thread-notes-db"
database_id = "b13731da-8916-4a2c-a96d-84272ff9da29"
migrations_dir = "drizzle"

# NOTE: Environment variables for production
[env.production]
name = "thread-note-backend-production"

[[env.production.d1_databases]]
binding = "DB"
database_name = "thread-notes-db-production"
database_id = "92003a61-32e5-4b53-8808-20d1e27191d8"
migrations_dir = "drizzle"

# NOTE: Development environment with local D1
[env.staging]
name = "thread-note-backend-staging"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "thread-notes-db-staging"
database_id = "acfb6ef5-b62e-4858-b956-e46965bdfb92"
migrations_dir = "drizzle"

# NOTE: Observability
[observability]
enabled = true
