openapi: 3.0.0
info:
  title: Thread-Based Note API
  version: 1.0.0
  description: API for managing threaded notes with mentions

servers:
  - url: http://localhost:3000/api
    description: Development server

paths:
  /notes:
    get:
      summary: List root notes
      description: Get paginated list of root notes (no parent)
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
            maximum: 100
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: List of notes
          content:
            application/json:
              schema:
                type: object
                properties:
                  notes:
                    type: array
                    items:
                      $ref: '#/components/schemas/Note'
                  total:
                    type: integer
                  hasMore:
                    type: boolean

    post:
      summary: Create a new note
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: string
                  minLength: 1
                  maxLength: 10000
                parentId:
                  type: string
                  pattern: '^[A-Za-z0-9]{6}$'
      responses:
        '201':
          description: Note created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /notes/{id}:
    get:
      summary: Get note with thread
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            pattern: '^[A-Za-z0-9]{6}$'
        - name: includeThread
          in: query
          schema:
            type: boolean
            default: true
      responses:
        '200':
          description: Note details
          content:
            application/json:
              schema:
                type: object
                properties:
                  note:
                    $ref: '#/components/schemas/Note'
                  thread:
                    type: array
                    items:
                      $ref: '#/components/schemas/Note'
        '404':
          description: Note not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Update note content
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: string
                  minLength: 1
                  maxLength: 10000
      responses:
        '200':
          description: Note updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
        '404':
          description: Note not found

    delete:
      summary: Delete note and its replies
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Note deleted
        '404':
          description: Note not found

  /notes/search:
    get:
      summary: Search notes
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
            minLength: 1
        - name: type
          in: query
          schema:
            type: string
            enum: [content, mention]
            default: content
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Note'
                  total:
                    type: integer

  /notes/{id}/mentions:
    get:
      summary: Get notes mentioning this note
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of mentioning notes
          content:
            application/json:
              schema:
                type: object
                properties:
                  mentions:
                    type: array
                    items:
                      type: object
                      properties:
                        note:
                          $ref: '#/components/schemas/Note'
                        position:
                          type: integer

components:
  schemas:
    Note:
      type: object
      required:
        - id
        - content
        - createdAt
        - updatedAt
        - depth
      properties:
        id:
          type: string
          pattern: '^[A-Za-z0-9]{6}$'
          example: 'a3k7m9'
        content:
          type: string
          minLength: 1
          maxLength: 10000
          example: 'This is a note with @a3k7m9 mention'
        parentId:
          type: string
          nullable: true
          pattern: '^[A-Za-z0-9]{6}$'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        depth:
          type: integer
          minimum: 0
          maximum: 100
        replyCount:
          type: integer
          minimum: 0
        mentions:
          type: array
          items:
            type: string
            pattern: '^[A-Za-z0-9]{6}$'

    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
        message:
          type: string
        details:
          type: object
